/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AppInfoResponse implements Serializable {


    @ColumnAlias("ID")
    private Integer id;

    @ColumnAlias("DESC")
    private String _desc;

    @ColumnAlias("CATEGORY_ID")
    private Integer categoryId;

    @ColumnAlias("CREATED_BY")
    private String createdBy;

    @ColumnAlias("CREATION_DATE")
    private Timestamp creationDate;

        @JsonView(BlobAsUrlView.class)
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("IMAGE")
    private byte[] image;

    @ColumnAlias("LAST_UPDATE_DATE")
    private Timestamp lastUpdateDate;

    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("UPDATED_BY")
    private String updatedBy;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String get_desc() {
        return this._desc;
    }

    public void set_desc(String _desc) {
        this._desc = _desc;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public Timestamp getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Timestamp lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AppInfoResponse)) return false;
        final AppInfoResponse appInfoResponse = (AppInfoResponse) o;
        return Objects.equals(getId(), appInfoResponse.getId()) &&
                Objects.equals(get_desc(), appInfoResponse.get_desc()) &&
                Objects.equals(getCategoryId(), appInfoResponse.getCategoryId()) &&
                Objects.equals(getCreatedBy(), appInfoResponse.getCreatedBy()) &&
                Objects.equals(getCreationDate(), appInfoResponse.getCreationDate()) &&
                Objects.equals(getImage(), appInfoResponse.getImage()) &&
                Objects.equals(getLastUpdateDate(), appInfoResponse.getLastUpdateDate()) &&
                Objects.equals(getName(), appInfoResponse.getName()) &&
                Objects.equals(getUpdatedBy(), appInfoResponse.getUpdatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                get_desc(),
                getCategoryId(),
                getCreatedBy(),
                getCreationDate(),
                getImage(),
                getLastUpdateDate(),
                getName(),
                getUpdatedBy());
    }
}