/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AppScreenshotsResponse implements Serializable {


    @ColumnAlias("ID")
    private Integer id;

    @ColumnAlias("APP_INFO_ID")
    private Integer appInfoId;

    @ColumnAlias("SCREENSHOTS")
    private String screenshots;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAppInfoId() {
        return this.appInfoId;
    }

    public void setAppInfoId(Integer appInfoId) {
        this.appInfoId = appInfoId;
    }

    public String getScreenshots() {
        return this.screenshots;
    }

    public void setScreenshots(String screenshots) {
        this.screenshots = screenshots;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AppScreenshotsResponse)) return false;
        final AppScreenshotsResponse appScreenshotsResponse = (AppScreenshotsResponse) o;
        return Objects.equals(getId(), appScreenshotsResponse.getId()) &&
                Objects.equals(getAppInfoId(), appScreenshotsResponse.getAppInfoId()) &&
                Objects.equals(getScreenshots(), appScreenshotsResponse.getScreenshots());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getAppInfoId(),
                getScreenshots());
    }
}