/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AvgratingResponse implements Serializable {


    @ColumnAlias("AVG(RATE)")
    private Double avg_rate_;

    public Double getAvg_rate_() {
        return this.avg_rate_;
    }

    public void setAvg_rate_(Double avg_rate_) {
        this.avg_rate_ = avg_rate_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AvgratingResponse)) return false;
        final AvgratingResponse avgratingResponse = (AvgratingResponse) o;
        return Objects.equals(getAvg_rate_(), avgratingResponse.getAvg_rate_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAvg_rate_());
    }
}