/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ChangePasswordRequest implements Serializable {


    @JsonProperty("newpassword")
    @NotNull
    private String newpassword;

    @JsonProperty("uname")
    @NotNull
    private String uname;

    @JsonProperty("oldpassword")
    @NotNull
    private String oldpassword;

    public String getNewpassword() {
        return this.newpassword;
    }

    public void setNewpassword(String newpassword) {
        this.newpassword = newpassword;
    }

    public String getUname() {
        return this.uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getOldpassword() {
        return this.oldpassword;
    }

    public void setOldpassword(String oldpassword) {
        this.oldpassword = oldpassword;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ChangePasswordRequest)) return false;
        final ChangePasswordRequest changePasswordRequest = (ChangePasswordRequest) o;
        return Objects.equals(getNewpassword(), changePasswordRequest.getNewpassword()) &&
                Objects.equals(getUname(), changePasswordRequest.getUname()) &&
                Objects.equals(getOldpassword(), changePasswordRequest.getOldpassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNewpassword(),
                getUname(),
                getOldpassword());
    }
}
