/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class EditUserRequest implements Serializable {


    @JsonProperty("newusername")
    @NotNull
    private String newusername;

    @JsonProperty("password")
    @NotNull
    private String password;

    @JsonProperty("urole")
    @NotNull
    private String urole;

    @JsonProperty("currentusername")
    @NotNull
    private String currentusername;

    public String getNewusername() {
        return this.newusername;
    }

    public void setNewusername(String newusername) {
        this.newusername = newusername;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUrole() {
        return this.urole;
    }

    public void setUrole(String urole) {
        this.urole = urole;
    }

    public String getCurrentusername() {
        return this.currentusername;
    }

    public void setCurrentusername(String currentusername) {
        this.currentusername = currentusername;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EditUserRequest)) return false;
        final EditUserRequest editUserRequest = (EditUserRequest) o;
        return Objects.equals(getNewusername(), editUserRequest.getNewusername()) &&
                Objects.equals(getPassword(), editUserRequest.getPassword()) &&
                Objects.equals(getUrole(), editUserRequest.getUrole()) &&
                Objects.equals(getCurrentusername(), editUserRequest.getCurrentusername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNewusername(),
                getPassword(),
                getUrole(),
                getCurrentusername());
    }
}