/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SelectfromAppsourceResponse implements Serializable {


    @ColumnAlias("ID")
    private Integer id;

    @ColumnAlias("FILE_PATH")
    private String filePath;

    @ColumnAlias("APP_INFO_ID")
    private Integer appInfoId;

    @ColumnAlias("CREATED_BY")
    private String createdBy;

    @ColumnAlias("CREATION_DATE")
    private Timestamp creationDate;

    @ColumnAlias("LAST_UPDATE_DATE")
    private Timestamp lastUpdateDate;

    @ColumnAlias("PRICE")
    private Integer price;

    @ColumnAlias("UPDATED_BY")
    private String updatedBy;

    @ColumnAlias("VERSION_ID")
    private Integer versionId;

    @ColumnAlias("FILE_NAME")
    private String fileName;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Integer getAppInfoId() {
        return this.appInfoId;
    }

    public void setAppInfoId(Integer appInfoId) {
        this.appInfoId = appInfoId;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    public Timestamp getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Timestamp lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersionId() {
        return this.versionId;
    }

    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SelectfromAppsourceResponse)) return false;
        final SelectfromAppsourceResponse selectfromAppsourceResponse = (SelectfromAppsourceResponse) o;
        return Objects.equals(getId(), selectfromAppsourceResponse.getId()) &&
                Objects.equals(getFilePath(), selectfromAppsourceResponse.getFilePath()) &&
                Objects.equals(getAppInfoId(), selectfromAppsourceResponse.getAppInfoId()) &&
                Objects.equals(getCreatedBy(), selectfromAppsourceResponse.getCreatedBy()) &&
                Objects.equals(getCreationDate(), selectfromAppsourceResponse.getCreationDate()) &&
                Objects.equals(getLastUpdateDate(), selectfromAppsourceResponse.getLastUpdateDate()) &&
                Objects.equals(getPrice(), selectfromAppsourceResponse.getPrice()) &&
                Objects.equals(getUpdatedBy(), selectfromAppsourceResponse.getUpdatedBy()) &&
                Objects.equals(getVersionId(), selectfromAppsourceResponse.getVersionId()) &&
                Objects.equals(getFileName(), selectfromAppsourceResponse.getFileName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getFilePath(),
                getAppInfoId(),
                getCreatedBy(),
                getCreationDate(),
                getLastUpdateDate(),
                getPrice(),
                getUpdatedBy(),
                getVersionId(),
                getFileName());
    }
}