/*Copyright (c) 2015-2016 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.wm_app_store.wm_app_store.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.wm_app_store.wm_app_store.models.query.EditUserRequest;

public interface WM_APP_STOREQueryExecutorService {

    Integer executeEditUser(EditUserRequest editUserRequest);

}